#!/bin/sh
### BEGIN INIT INFO
# Provides:          zrlogwww
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       <DESCRIPTION>
### END INIT INFO

BASEPATH=/var/lib/zrlogwww

SCRIPT=sh ${BASEPATH}/start.sh
RUNAS=zrlogwww

PIDFILE=${BASEPATH}/sim.pid
LOGFILE=${BASEPATH}/log/zrlogwww.log

start() {
  # shellcheck disable=SC2046
  echo 'Starting service…' >&2
  # shellcheck disable=SC2039
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  # shellcheck disable=SC2046
  if [ ! -f ${PIDFILE} ] || ! kill -9 $(cat ${PIDFILE}); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  # shellcheck disable=SC2046
  kill -15 $(cat ${PIDFILE}) && rm -f ${PIDFILE}
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
